output:
  print-issued-lines: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - unused
    - gocognit
    - gocritic
    - prealloc
    - unparam
    - nakedret
    - exportloopref
    - gocyclo
    - revive
    - govet
    - errcheck
    - dupl
    - ineffassign
    - unconvert
    - goconst
    - gosec
    - megacheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: '(.+)_test\.go'
      # don't lint test files using dupl linter because they have a lot of duplications
      linters:
        - dupl
      source: "^//go:generate "
