// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package filerepository is a generated GoMock package.
package filerepository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddChunk mocks base method.
func (m *MockRepository) AddChunk(arg Chunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChunk", arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddChunk indicates an expected call of AddChunk.
func (mr *MockRepositoryMockRecorder) AddChunk(arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChunk", reflect.TypeOf((*MockRepository)(nil).AddChunk), arg)
}

// AllChunksUploadedForUUID mocks base method.
func (m *MockRepository) AllChunksUploadedForUUID(deliveryUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllChunksUploadedForUUID", deliveryUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllChunksUploadedForUUID indicates an expected call of AllChunksUploadedForUUID.
func (mr *MockRepositoryMockRecorder) AllChunksUploadedForUUID(deliveryUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllChunksUploadedForUUID", reflect.TypeOf((*MockRepository)(nil).AllChunksUploadedForUUID), deliveryUUID)
}
