name: CI on pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:      
    - name: Git clone repo
      uses: actions/checkout@v1

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m --config .golangci.yaml   --issues-exit-code=0 
  
  test:
    runs-on: ubuntu-latest
    steps:      
    - name: Git clone repo
      uses: actions/checkout@v1

    - name: Run tests
      run: |
        make test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:      
    - name: Git clone repo
      uses: actions/checkout@v1

    - name: Install golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Build binary progect
      run: |
        make compile
